## AirPhysics (PhysicsBase)
##
## Physics controller for aircraft (planes, helicopters, VTOL craft).
##
## Flight model:
##   - **Lift** is generated by wing area and airspeed:
##       Lift = wing_area * speed^2 * 0.5 * lift_coefficient
##     This is a simplified version of the real lift equation
##     (L = 0.5 * rho * v^2 * S * Cl). We fold air density and angle of
##     attack into the single lift_coefficient tunable.
##   - **Stall**: below stall_speed, lift drops sharply and the aircraft sinks.
##   - **Drag**: opposes the velocity vector, proportional to speed^2.
##       Drag_force = total_drag * speed^2
##   - **Bank-to-turn**: rolling the aircraft causes yaw proportional to the
##     roll angle, like a real plane. Pulling the stick back (pitch up) while
##     banked turns the velocity vector.
##   - **Throttle**: controlled separately from pitch/roll (Shift / Ctrl or
##     dedicated throttle actions). Thrust = total_thrust * throttle.
##   - **Altitude limits**: a ceiling and a minimum altitude prevent the player
##     from flying into orbit or clipping through the terrain.
class_name AirPhysics
extends PhysicsBase


# ---------------------------------------------------------------------------
# Tuning constants
# ---------------------------------------------------------------------------

## Lift coefficient. Higher = more lift per unit wing area and speed.
## 0.5 is a reasonable arcade value for a medium-weight fighter.
var lift_coefficient: float = 0.5

## Speed (m/s) below which the aircraft begins to stall. At stall, lift is
## dramatically reduced and the plane sinks.
var stall_speed: float = 15.0

## Maximum altitude (meters above origin). Above this, thrust is reduced to
## prevent escaping the arena.
var altitude_ceiling: float = 2000.0

## Minimum altitude. A spring force pushes the aircraft up if it drops below
## this height, preventing ground clipping.
var min_altitude: float = 5.0

## Current altitude cached each frame for HUD display and logic.
var current_altitude: float = 0.0

## Throttle setting: 0.0 (idle) to 1.0 (full power).
var throttle: float = 0.0

## True when the aircraft is below stall speed and above min_altitude.
var is_stalling: bool = false


# ---------------------------------------------------------------------------
# Constants (internal)
# ---------------------------------------------------------------------------

## How quickly the throttle responds to input (per second).
const THROTTLE_RATE: float = 0.8

## Pitch / roll torque magnitude applied per unit of stick input.
const PITCH_TORQUE: float = 8.0
const ROLL_TORQUE: float = 12.0

## How strongly roll angle converts into yaw (bank-to-turn coupling).
const BANK_TO_YAW_FACTOR: float = 3.0

## Spring constant for the ground-proximity safety push.
const GROUND_SPRING_K: float = 50.0

## Drag multiplier during a stall (much higher drag = nose drops fast).
const STALL_DRAG_MULTIPLIER: float = 3.0


# ---------------------------------------------------------------------------
# PhysicsBase overrides
# ---------------------------------------------------------------------------

## Apply aerodynamic forces every physics frame.
func apply_forces(vehicle: RigidBody3D, delta: float) -> void:
	var speed: float = vehicle.linear_velocity.length()
	current_altitude = vehicle.global_position.y
	var wing: float = _get_wing_area(vehicle)

	# --- Throttle input ---
	var input: Dictionary = vehicle.get_input_vector()
	if input.get("throttle_up", false):
		throttle = clampf(throttle + THROTTLE_RATE * delta, 0.0, 1.0)
	elif input.get("throttle_down", false):
		throttle = clampf(throttle - THROTTLE_RATE * delta, 0.0, 1.0)

	# --- Thrust ---
	# Thrust acts in the aircraft's forward direction (-Z in local space).
	var thrust_magnitude: float = vehicle.total_thrust * throttle
	var forward: Vector3 = vehicle.get_forward_direction()
	vehicle.apply_central_force(forward * thrust_magnitude)

	# --- Lift ---
	# Lift = wing_area * v^2 * 0.5 * lift_coefficient.
	# Lift acts along the aircraft's local UP direction (countering gravity).
	var lift_force: float = wing * speed * speed * 0.5 * lift_coefficient

	# Stall check: if speed is below stall_speed and we're not on the ground,
	# dramatically reduce lift so the nose drops.
	is_stalling = (speed < stall_speed) and (current_altitude > min_altitude)
	if is_stalling:
		# Reduce lift to 20% during a stall.
		lift_force *= 0.2

	var up_dir: Vector3 = vehicle.global_transform.basis.y
	vehicle.apply_central_force(up_dir * lift_force)

	# --- Drag ---
	# Drag opposes the velocity vector. F_drag = drag_coeff * v^2.
	if speed > 0.1:
		var drag_coeff: float = vehicle.total_drag
		if is_stalling:
			drag_coeff *= STALL_DRAG_MULTIPLIER
		var drag_force: float = drag_coeff * speed * speed
		var drag_dir: Vector3 = -vehicle.linear_velocity.normalized()
		vehicle.apply_central_force(drag_dir * drag_force)

	# --- Bank-to-turn ---
	# When the aircraft is rolled, apply a yaw torque proportional to the
	# roll angle. This makes banked turns feel natural.
	var roll_angle: float = vehicle.global_transform.basis.z.dot(Vector3.UP)
	# roll_angle is approximately sin(roll) -- negative = rolling right.
	var bank_yaw: float = -roll_angle * BANK_TO_YAW_FACTOR * speed * 0.1
	vehicle.apply_torque(vehicle.global_transform.basis.y * bank_yaw)

	# --- Altitude limits ---
	# Ceiling: reduce thrust above the ceiling.
	if current_altitude > altitude_ceiling:
		var over: float = current_altitude - altitude_ceiling
		vehicle.apply_central_force(Vector3.DOWN * over * 10.0)

	# Ground proximity: push up if too low.
	if current_altitude < min_altitude:
		var under: float = min_altitude - current_altitude
		vehicle.apply_central_force(Vector3.UP * under * GROUND_SPRING_K)


## Translate player input into pitch and roll torques.
func handle_input(vehicle: RigidBody3D, _delta: float) -> void:
	var input: Dictionary = vehicle.get_input_vector()
	var pitch_input: float = input.get("pitch", 0.0)
	var roll_input: float = input.get("roll", 0.0)

	# Pitch: rotate around the local X axis.
	# Positive pitch_input = nose up.
	var local_x: Vector3 = vehicle.global_transform.basis.x
	vehicle.apply_torque(local_x * pitch_input * PITCH_TORQUE * vehicle.total_mass)

	# Roll: rotate around the local Z axis.
	# Positive roll_input = roll right.
	var local_z: Vector3 = vehicle.global_transform.basis.z
	vehicle.apply_torque(local_z * -roll_input * ROLL_TORQUE * vehicle.total_mass)


## Theoretical top speed: the speed at which thrust equals drag.
## thrust = drag_coeff * v^2  =>  v = sqrt(thrust / drag_coeff).
func get_max_speed(vehicle: RigidBody3D) -> float:
	var d: float = maxf(vehicle.total_drag, 0.01)
	return sqrt(vehicle.total_thrust / d)


## Return "air".
func get_domain() -> String:
	return "air"


## HUD data for aircraft: speed, altitude, throttle, stall status, heading,
## and pitch angle.
func get_hud_data(vehicle: RigidBody3D) -> Dictionary:
	var speed: float = get_current_speed(vehicle)
	var fwd: Vector3 = vehicle.get_forward_direction()

	# Heading: angle in the XZ plane, 0 = north (+Z).
	var heading: float = rad_to_deg(atan2(fwd.x, fwd.z))
	if heading < 0.0:
		heading += 360.0

	# Pitch angle: degrees above/below the horizon.
	var pitch_angle: float = rad_to_deg(asin(clampf(fwd.y, -1.0, 1.0)))

	return {
		"speed": speed,
		"max_speed": get_max_speed(vehicle),
		"altitude": current_altitude,
		"throttle": throttle,
		"is_stalling": is_stalling,
		"heading": heading,
		"pitch_angle": pitch_angle,
	}


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

## Compute the effective wing area from the vehicle's parts.
## Aerodynamic frame parts each contribute approximately 2.0 m^2.
## Uses a seen-set to avoid double-counting multi-cell parts that occupy
## more than one grid cell in the parts dictionary.
func _get_wing_area(vehicle: RigidBody3D) -> float:
	var area: float = 0.0
	var seen: Dictionary = {}

	# Check propulsion parts first (engines with wings, etc.).
	for part: PartNode in vehicle.propulsion_parts:
		if part.part_data == null:
			continue
		seen[part.get_instance_id()] = true
		if part.part_data.subcategory in ["wing", "aerodynamic_frame"]:
			area += 2.0

	# Also check non-propulsion parts (wings might be in chassis category).
	# Deduplicate via instance ID since multi-cell parts appear multiple times
	# in vehicle.parts.
	for cell_pos: Vector3i in vehicle.parts:
		var pn: PartNode = vehicle.parts[cell_pos]
		var nid: int = pn.get_instance_id()
		if seen.has(nid):
			continue
		seen[nid] = true
		if pn.part_data == null:
			continue
		if pn.part_data.subcategory in ["wing", "aerodynamic_frame"]:
			area += 2.0

	return area
